### ISSUE TITLE
msg Receive timeout. with brocade_fos_command

### ISSUE THREAD

**Issue by kevinhuy** [chipcopper/ansible-fos-command#3]
Hi

My environnement

ansible 2.9.1
python 2.7

i have random timeout issue when trying this playbook :

name: firmwaredownloadstatus
brocade_fos_command:
switch_login: admin
switch_password: XXXXX
switch_address: X.X.X.X
command_set:
- command: firmwareshow
timeout: 120
register: check_version

name: print ansible_facts gathered
debug:
var: check_version

I also noticed that before upgrade to 8.2 the command did not have time to execute properly.

Error below

TASK [firmwaredownloadstatus] ***************************************************************************************************************************************
task path: /home/xxx/git/ansible/brocade/tasks/test2.yml:12
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "echo /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860" && echo ansible-tmp-1578993312.91-86715209149860="echo /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860" ) && sleep 0'
Using module file /home/xxx/git/ansible/brocade/library/brocade_fos_command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-255796hHpRt/tmp85CEV6 TO /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/AnsiballZ_brocade_fos_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/ /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1578993312.91-86715209149860/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may not be related to the actual failure.
File "/tmp/ansible_brocade_fos_command_payload_RcfS5j/ansible_brocade_fos_command_payload.zip/ansible/modules/brocade_fos_command.py", line 322, in receive_until_match
File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 667, in recv
raise socket.timeout()

[WARNING]: Module did not set no_log for switch_password

fatal: [localhost]: FAILED! => {
"changed": false,
"invocation": {
"module_args": {
"command_set": [
{
"command": "firmwareshow",
"exit_tests": [],
"prompts": [],
"result_tests": [],
"start_state": [
{
"flag": "changed",
"value": false
},
{
"flag": "failed",
"value": false
}
],
"timeout": 120
}
],
"global_timeout": 15,
"hostkeymust": false,
"switch_address": "",
"switch_login": "admin",
"switch_password": ""
}
},
"messages": [
"",
"SSH into X.X.X.X",
"Exiting due to error: ",
[
"firmwareshow",
"Appl Primary/Secondary Versions ",
"------------------------------------------",
"FOS v8.2.1c",
" v8.2.1c",
"DS_6505B:admin> "
]

**Comment by chipcopper** [comment]
Hi kevinhuy,

Has the playbook ever run successfully?  If so, then that reinforces the idea that it is a timer problem.  If it has not, then has any other command ever run successfully?

I have seen this before on a busy switch.  As a first attempt, change the time on line 275 from 5 seconds to say 20 and let me know what happens.

**Comment by kevinhuy** [comment]
Indeed it has run successfully, but it is random. 

Envoyé de mon iPhone

**Comment by chipcopper** [comment]
That's good news!  The behavior of the switch, module, and playbook are deterministic - the variable is timing - especially for capturing the prompt.  Let me know what happens when you have a chance to increase the time in line 275 to 20.

Let me give you some insight on what is happening.  If you look at your trace, you will see in the messages section that the command executed successfully and the shell was back at the command prompt.  The prompt, however, was not recognized by the script.  Typically this happens when the login process on the switch takes longer than expected and the script does not get a clean copy of the prompt.  That is why increasing the time in line 275 helps.  It gives the switch more time to finish the login process, print the banner, and get to the prompt state.  The next newline should produce a clean copy of the CLI prompt which the script captures.

Can you please tell me the switch model and verify the version of FOS you are running this against?  (You mentioned 8.2 but is it 8.2.0, 8.2.1a, etc.)

Thanks, and I will look for your trace after you have made the suggested change.

**Comment by kevinhuy** [comment]
hi 

you right , it is much much better. I have retries aaaconfig without error. 
I m running in switch model 6505 / Factory Part Num:  40-1000737-04 from chassishow

I will test firmwaredownload again tomorrrow and give you feedback. 

Below my stack

TASK [configure radius client] **************************************************************************************************************************************
task path: /home/khuy/git/ansible/brocade/tasks/fr2-sw1.yml:79
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1579043446.51-42463663599408 `" && echo ansible-tmp-1579043446.51-42463663599408="` echo /root/.ansible/tmp/ansible-tmp-1579043446.51-42463663599408 `" ) && sleep 0'
Using module file /home/khuy/git/ansible/brocade/library/brocade_fos_command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-13893n_gfUf/tmpz_4Mim TO /root/.ansible/tmp/ansible-tmp-1579043446.51-42463663599408/AnsiballZ_brocade_fos_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1579043446.51-42463663599408/ /root/.ansible/tmp/ansible-tmp-1579043446.51-42463663599408/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1579043446.51-42463663599408/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1579043446.51-42463663599408/ > /dev/null 2>&1 && sleep 0'
[WARNING]: Module did not set no_log for switch_password

ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command_set": [
                {
                    "command": "aaaconfig --add  X.X.X.X  -conf radius -p 1812 -s XXXXXXX -t 15 -a pap",
                    "exit_tests": [
                        "exists"
                    ],
                    "prompts": [
                        {
                            "question": "Encryption type is currently set to none. Do you want to set encryption type to aes256? (y/n)",
                            "response": "Y"
                        }
                    ],
                    "result_tests": [],
                    "start_state": [
                        {
                            "flag": "changed",
                            "value": false
                        },
                        {
                            "flag": "failed",
                            "value": false
                        }
                    ],
                    "timeout": 60
                }
            ],
            "global_timeout": 15,
            "hostkeymust": false,
            "switch_address": "X.X.X.X",
            "switch_login": "admin",
            "switch_password": "X.X.X.X"
        }
    },
    "messages": [
        "sans01:admin> aaaconfig --add  X.X.X.X  -conf radius -p 1812  \r-s xxxxxxxxx -t 15 -a pap",
        "",
        "Encryption type is currently set to none. Do you want to set encryption type to aes256? (y/n):Y",
        "sans01:admin> "
    ]
}

TASK [configure radius authentification order] **********************************************************************************************************************
task path: /home/khuy/git/ansible/brocade/tasks/fr2-sw1.yml:94
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1579043470.25-205236408041029 `" && echo ansible-tmp-1579043470.25-205236408041029="` echo /root/.ansible/tmp/ansible-tmp-1579043470.25-205236408041029 `" ) && sleep 0'
Using module file /home/khuy/git/ansible/brocade/library/brocade_fos_command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-13893n_gfUf/tmp5IlQ6w TO /root/.ansible/tmp/ansible-tmp-1579043470.25-205236408041029/AnsiballZ_brocade_fos_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1579043470.25-205236408041029/ /root/.ansible/tmp/ansible-tmp-1579043470.25-205236408041029/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1579043470.25-205236408041029/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1579043470.25-205236408041029/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command_set": [
                {
                    "command": "aaaconfig --authspec \"radius;local\"",
                    "exit_tests": [
                        "AUTH configuration already enabled"
                    ],
                    "prompts": [],
                    "result_tests": [],
                    "start_state": [
                        {
                            "flag": "changed",
                            "value": false
                        },
                        {
                            "flag": "failed",
                            "value": false
                        }
                    ],
                    "timeout": 60
                }
            ],
            "global_timeout": 15,
            "hostkeymust": false,
            "switch_address": "X.X.X.X",
            "switch_login": "admin",
            "switch_password": "X.X.X.X"
        }
    },
    "messages": [
        "sansw01:admin> aaaconfig --authspec \"radius;local\"",
        "sansw01:admin> "
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=9    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by kevinhuy** [comment]
Also i would like to use ansible fos command for changing password , but at first switch initialization we are asking to change password with enter like below 


-----------------------------------------------------------------
Warning: Default password not changed for 'root'. Please login as 'root' to change it.
Please change passwords for switch default accounts now.
Use Control-C to exit or press 'Enter' key to proceed.

Is there a way to use ansible fos command to simulate 'Enter Key' and change password for user and admin ?

**Comment by chipcopper** [comment]
I looked at the traces that you sent in the other two issues and I am optimistic that adjusting this timing may take care of the issue.  Let me know after you try them.

Let me think about the initial changing of the password request.  I know how to do it but the problem will be testing it - getting the switch to reset the request a number of times so that I can be sure it works reliably.  I have to look around to see if I can reset the nag.  If I decide to chase that down, it will be a different module rather than complicating this one.  I'm big on the keep-it-simple design philosophy.

**Comment by kevinhuy** [comment]
i will deploy 2 other new switch, let me know if u need support for test.

**Comment by chipcopper** [comment]
It appears the issue was resolved by changing the timer as described above.
