### ISSUE TITLE
Errror with brocade_fos_command in order to configure aaaconfig / radius

### ISSUE THREAD

**Issue by kevinhuy** [chipcopper/ansible-fos-command#4]
Hi

My environnement below:

ansible 2.9.1
python 2.7

When i try to execute this task below , at first attempt i have always an error. The command is executed but failed so i cannot in continu other tasks.

  - name: configure radius client
    brocade_fos_command:
      switch_login: "{{ credential.fos_user_name }}"
      switch_password: "{{ credential.fos_password }}"
      switch_address: "{{ credential.fos_ip_addr }}"
      command_set:
        #
        - command: aaaconfig --add  {{ radius_server1 }}  -conf radius -p 1812 -s {{ my_pass }} -t 15 -a pap
          prompts:
            - question: Encryption type is currently set to none. Do you want to set encryption type to aes256? (y/n)
              response: Y
          exit_tests:
            - exists
          timeout: 60

Error below:

<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1579027290.18-185255235262549/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_brocade_fos_command_payload_xb8CGt/ansible_brocade_fos_command_payload.zip/ansible/modules/brocade_fos_command.py", line 322, in receive_until_match
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 667, in recv
    raise socket.timeout()

[WARNING]: Module did not set no_log for switch_password

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command_set": [
                {
                    "command": "aaaconfig --add  172.31.36.10  -conf radius -p 1812 -s XXXXXXX -t 15 -a pap",
                    "exit_tests": [
                        "exists"
                    ],
                    "prompts": [
                        {
                            "question": "Encryption type is currently set to none. Do you want to set encryption type to aes256? (y/n)",
                            "response": "Y"
                        }
                    ],
                    "result_tests": [],
                    "start_state": [
                        {
                            "flag": "changed",
                            "value": false
                        },
                        {
                            "flag": "failed",
                            "value": false
                        }
                    ],
                    "timeout": 60
                }
            ],
            "global_timeout": 15,
            "hostkeymust": false,
            "switch_address": "X.X.X.X",
            "switch_login": "admin",
            "switch_password": "XXXXX"
        }
    },
    "messages": [
        "",
        "SSH into X.X.X.X",
        "Exiting due to error: ",

**Comment by chipcopper** [comment]
Deferring until we get #3 resolved.

**Comment by chipcopper** [comment]
Resolved in #3.
