### ISSUE TITLE
Errror with brocade_fos_command with firmwaredownload

### ISSUE THREAD

**Issue by kevinhuy** [chipcopper/ansible-fos-command#5]
Hi

My environnement

ansible 2.9.1
python 2.7

My playbook is trying to upgrade switch san. The first upgrade is properly executed, but the second is failed because of quote or timing issue.

tasks 

---
- hosts: localhost
  gather_facts: False

  vars:

    update1: v8.1.0a
    update2: v8.2.1c
    sw_ip : X.X.X.X

  tasks:

  - name: Update firmware to {{ update1 }}
    brocade_fos_command:
      switch_login: admin
      switch_password: XXXXX
      switch_address: "{{ sw_ip }}"
      command_set:
        # 
        - command: firmwaredownload -p ftp X.X.X.X,XXX,{{ update1 }},XXXXX
          prompts:
            - question: Do you want to continue
              response: "Y"
          exit_tests:
            - Failed
            - failed
            - Rebooting
            - rebooting
          timeout: 120
    register: configout

  - name: print ansible_facts gathered
    debug:
      var: configout

  - pause:
      minutes: 10

  - name: Update firmware to {{ update2 }}
    brocade_fos_command:
      switch_login: admin
      switch_password: XXXXX
      switch_address: "{{ sw_ip }}"
      command_set:
        #
        - command: firmwaredownload -p ftp X.X.X.X,XXXX,{{ update2 }},XXXXX
          prompts:
            - question: Do you want to continue
              response: "Y"
          exit_tests:
            - Failed
            - failed
            - Rebooting
            - rebooting
          timeout: 120
    register: configout

  - name: print ansible_facts gathered
    debug:
      var: configout

Error stack below

[root@kfr-infnwb-s01 tasks]# ansible-playbook firmwaredownload.yml -vvv
ansible-playbook 2.9.1
  config file = /home/khuy/git/ansible/brocade/tasks/ansible.cfg
  configured module search path = [u'/home/khuy/git/ansible/brocade/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /home/khuy/git/ansible/brocade/tasks/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAYBOOK: firmwaredownload.yml *******************************************************************************************************************************
1 plays in firmwaredownload.yml

PLAY [localhost] ****************************************************************************************************************************************************
META: ran handlers

TASK [Update firmware to v8.1.0a] ***********************************************************************************************************************************
task path: /home/khuy/git/ansible/brocade/tasks/firmwaredownload.yml:13
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1578994590.8-72468703684507 `" && echo ansible-tmp-1578994590.8-72468703684507="` echo /root/.ansible/tmp/ansible-tmp-1578994590.8-72468703684507 `" ) && sleep 0'
Using module file /home/khuy/git/ansible/brocade/library/brocade_fos_command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-29482WAeVMj/tmpl_yVgK TO /root/.ansible/tmp/ansible-tmp-1578994590.8-72468703684507/AnsiballZ_brocade_fos_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1578994590.8-72468703684507/ /root/.ansible/tmp/ansible-tmp-1578994590.8-72468703684507/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1578994590.8-72468703684507/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1578994590.8-72468703684507/ > /dev/null 2>&1 && sleep 0'
[WARNING]: Module did not set no_log for switch_password

ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command_set": [
                {
                    "command": "firmwaredownload -p ftp X.X.X.X,XXXX,v8.1.0a,X.X.X.X",
                    "exit_tests": [
                        "Failed",
                        "failed",
                        "Rebooting",
                        "rebooting"
                    ],
                    "prompts": [
                        {
                            "question": "Do you want to continue",
                            "response": "Y"
                        }
                    ],
                    "result_tests": [],
                    "start_state": [
                        {
                            "flag": "changed",
                            "value": false
                        },
                        {
                            "flag": "failed",
                            "value": false
                        }
                    ],
                    "timeout": 120
                }
            ],
            "global_timeout": 15,
            "hostkeymust": false,
            "switch_address": "X.X.X.X.",
            "switch_login": "admin",
            "switch_password": "XXXXXX"
        }
    },
    "messages": [
        "DS_6505B:admin> firmwaredownload -p ftp X.X.X.X,khuy,v8.1.0a,XXXXX",
        "Server IP: X.X.X.X, Protocol IPv4",
        "Checking system settings for firmwaredownload...",
        "System settings check passed.",
        "",
        "You can run firmwaredownloadstatus to get the status",
        "of this command.",
        "",
        "This command will cause a warm/non-disruptive boot but will ",
        "require that existing telnet, secure telnet or SSH sessions ",
        "be restarted.",
        " ",
        "",
        "",
        "Do you want to continue (Y/N) [Y]: Y",
        "Firmware is being downloaded to the switch. This step may take up to 30 minutes.",
        "Preparing for firmwaredownload...",
        "Removing strace",
        "Removing sysstat",
        "Start to install packages...",
        Display OMIT
        "Please avoid powering off the system during prom update.",
        Display OMIT
        "Removing unneeded files, please wait ...",
        "Finished removing unneeded files. ",
        "",
        "All packages have been downloaded successfully.",
        "Firmware has been downloaded to the secondary partition of the switch.",
        "HA Rebooting ...",
        ""
    ]
}

TASK [print ansible_facts gathered] *********************************************************************************************************************************
task path: /home/khuy/git/ansible/brocade/tasks/firmwaredownload.yml:32
ok: [localhost] => {
    "configout": {
        "changed": false,
        "failed": false,
        "messages": [
            "DS_6505B:admin> firmwaredownload -p ftp X.X.X.X,khuy,v8.1.0a,XXXXX",
            "Server IP: X.X.X.X, Protocol IPv4",
            "Checking system settings for firmwaredownload...",
            "System settings check passed.",
            "",
            "You can run firmwaredownloadstatus to get the status",
            "of this command.",
            "",
            "This command will cause a warm/non-disruptive boot but will ",
            "require that existing telnet, secure telnet or SSH sessions ",
            "be restarted.",
            " ",
            "",
            "",
            "Do you want to continue (Y/N) [Y]: Y",
            "Firmware is being downloaded to the switch. This step may take up to 30 minutes.",
            "Preparing for firmwaredownload...",
            "Removing strace",
            "Removing sysstat",
            "Start to install packages...",
         Display OMIT
            "Removing unneeded files, please wait ...",
            "Finished removing unneeded files. ",
            "",
            "All packages have been downloaded successfully.",
            "Firmware has been downloaded to the secondary partition of the switch.",
            "HA Rebooting ...",
            ""
        ],
        "warnings": [
            "Module did not set no_log for switch_password"
        ]
    }
}

TASK [pause] ********************************************************************************************************************************************************
task path: /home/khuy/git/ansible/brocade/tasks/firmwaredownload.yml:36
Pausing for 600 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost] => {
    "changed": false,
    "delta": 600,
    "echo": true,
    "rc": 0,
    "start": "2020-01-14 10:41:26.719931",
    "stderr": "",
    "stdout": "Paused for 10.0 minutes",
    "stop": "2020-01-14 10:51:26.720491",
    "user_input": ""
}

TASK [Update firmware to v8.2.1c] ***********************************************************************************************************************************
task path: /home/khuy/git/ansible/brocade/tasks/firmwaredownload.yml:39
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1578995486.76-155114429433413 `" && echo ansible-tmp-1578995486.76-155114429433413="` echo /root/.ansible/tmp/ansible-tmp-1578995486.76-155114429433413 `" ) && sleep 0'
Using module file /home/khuy/git/ansible/brocade/library/brocade_fos_command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-29482WAeVMj/tmpaurEzI TO /root/.ansible/tmp/ansible-tmp-1578995486.76-155114429433413/AnsiballZ_brocade_fos_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1578995486.76-155114429433413/ /root/.ansible/tmp/ansible-tmp-1578995486.76-155114429433413/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1578995486.76-155114429433413/AnsiballZ_brocade_fos_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1578995486.76-155114429433413/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command_set": [
                {
                    "command": "firmwaredownload -p ftp X.X.X.X.,XXXX,v8.2.1c,XXXXX",
                    "exit_tests": [
                        "Failed",
                        "failed",
                        "Rebooting",
                        "rebooting"
                    ],
                    "prompts": [
                        {
                            "question": "Do you want to continue",
                            "response": "Y"
                        }
                    ],
                    "result_tests": [],
                    "start_state": [
                        {
                            "flag": "changed",
                            "value": false
                        },
                        {
                            "flag": "failed",
                            "value": false
                        }
                    ],
                    "timeout": 120
                }
            ],
            "global_timeout": 15,
            "hostkeymust": false,
            "switch_address": "X.X.X.X.",
            "switch_login": "admin",
            "switch_password": "XXXXX"
        }
    **},
    **"messages": [
        "DS_6505B:admin> ",
        "firmwaredownload -p ftp X.X.X.X.,XXXX,v8.2.1c,XXXXX",
        "DS_6505B:admin> ",
        ""****
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

**Comment by chipcopper** [comment]
Deferring until we get #3 resolved.

**Comment by chipcopper** [comment]
Resolved in #3.
